### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Tukali** [aetkrad/SearchHack#1]
chrome浏览器，打开开发者模式，默认不让使用，也无法强制打开

**Comment by aetkrad** [comment]
（1）可以查看下报什么错误。
（2）下载源代码，通过浏览器设置中的扩展程序中选择“加载已解压的扩展程序”来安装。
![image](https://user-images.githubusercontent.com/11288770/140466834-175b2733-343d-4a47-9cb7-2281ec66d498.png)
![image](https://user-images.githubusercontent.com/11288770/140466882-2dc84d76-700d-4de2-ae68-735fd3f36565.png)
（3）解压crx文件，通过浏览器设置中的扩展程序中选择“加载已解压的扩展程序”来安装。（同2）

**Comment by Tukali** [comment]
> （1）可以查看下报什么错误。 （2）下载源代码，通过浏览器设置中的扩展程序中选择“加载已解压的扩展程序”来安装。 ![image](https://user-images.githubusercontent.com/11288770/140466834-175b2733-343d-4a47-9cb7-2281ec66d498.png) ![image](https://user-images.githubusercontent.com/11288770/140466882-2dc84d76-700d-4de2-ae68-735fd3f36565.png) （3）解压crx文件，通过浏览器设置中的扩展程序中选择“加载已解压的扩展程序”来安装。（同2）
![image](https://user-images.githubusercontent.com/45891208/140467854-199eac01-e4b0-4ce9-8880-4c034de52149.png)
我是直接使用crx文件的，就这样无法使用，那我解压试试

**Comment by Tukali** [comment]
直接用解压的源码没问题了，谢谢师傅
